[2024-01-12T04:37:08.872+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Data_Ingestion.raw_zone manual__2024-01-12T04:37:05.137090+00:00 [queued]>
[2024-01-12T04:37:08.876+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Data_Ingestion.raw_zone manual__2024-01-12T04:37:05.137090+00:00 [queued]>
[2024-01-12T04:37:08.876+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-01-12T04:37:08.881+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): raw_zone> on 2024-01-12 04:37:05.137090+00:00
[2024-01-12T04:37:08.884+0000] {standard_task_runner.py:57} INFO - Started process 366 to run task
[2024-01-12T04:37:08.886+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Data_Ingestion', 'raw_zone', 'manual__2024-01-12T04:37:05.137090+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_layer.py', '--cfg-path', '/tmp/tmpzhdzlb_4']
[2024-01-12T04:37:08.889+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask raw_zone
[2024-01-12T04:37:08.913+0000] {task_command.py:415} INFO - Running <TaskInstance: Data_Ingestion.raw_zone manual__2024-01-12T04:37:05.137090+00:00 [running]> on host 9e5ee476ef7d
[2024-01-12T04:37:09.045+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thanatthuch724@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Data_Ingestion' AIRFLOW_CTX_TASK_ID='raw_zone' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T04:37:05.137090+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T04:37:05.137090+00:00'
[2024-01-12T04:37:09.060+0000] {logging_mixin.py:151} INFO -    yearMonth  ProductID  ... salesAmount  percentage_change
0    1996-07         17  ...       936.0                NaN
1    1996-07         40  ...       735.0                NaN
2    1996-07         60  ...      1088.0                NaN
3    1996-07          2  ...      1596.0                NaN
4    1996-07         39  ...       691.2                NaN
5    1996-07          5  ...      1309.0                NaN
6    1996-07         33  ...       170.0                NaN
7    1996-07         56  ...        60.8                NaN
8    1996-07         31  ...       200.0                NaN
9    1996-07         37  ...        20.8                NaN
10   1996-07         24  ...       154.8                NaN
11   1996-07         22  ...       100.8                NaN
12   1996-07         36  ...       380.0                NaN
13   1996-07         41  ...       392.7                NaN
14   1996-07         76  ...       216.0                NaN
15   1996-07         74  ...       456.0                NaN
16   1996-07         65  ...       588.0                NaN
17   1996-07         51  ...      3180.0                NaN
18   1996-07         32  ...       153.6                NaN
19   1996-07         49  ...       640.0                NaN
20   1996-07         72  ...       841.2                NaN
21   1996-07         30  ...      1242.0                NaN
22   1996-07         77  ...       280.8                NaN
23   1996-07         70  ...       492.0                NaN
24   1996-07         16  ...      1320.5                NaN
25   1996-07         53  ...       393.0                NaN
26   1996-07         55  ...       403.2                NaN
27   1996-07         11  ...       168.0                NaN
28   1996-07         12  ...       364.8                NaN
29   1996-07         59  ...      4400.0                NaN
30   1996-07         57  ...      1014.0                NaN
31   1996-07         27  ...       877.5                NaN
32   1996-07         42  ...        98.0                NaN
33   1996-07         20  ...      2592.0                NaN
34   1996-07         21  ...       240.0                NaN
35   1996-07         35  ...       288.0                NaN
36   1996-07         62  ...       591.0                NaN
37   1996-07         29  ...       990.0                NaN
38   1996-07         14  ...       167.4                NaN
39   1996-07          7  ...       360.0                NaN

[40 rows x 5 columns]
[2024-01-12T04:37:09.061+0000] {postgres.py:168} INFO - Running copy expert: COPY raw_staging.ProductSalesAmountByMonth (yearMonth, ProductId, ProductName, salesAmount, percentage_change)
        FROM stdin WITH CSV HEADER
        DELIMITER as ',
    ', filename: /opt/***/data/1996Jul.csv
[2024-01-12T04:37:09.064+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-12T04:37:09.067+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_layer.py", line 57, in load_data_raw_zone
    pg_hook_load.copy_expert(sql=sql, filename=file_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.FeatureNotSupported: COPY delimiter must be a single one-byte character

[2024-01-12T04:37:09.072+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=Data_Ingestion, task_id=raw_zone, execution_date=20240112T043705, start_date=20240112T043708, end_date=20240112T043709
[2024-01-12T04:37:09.078+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-01-12T04:37:09.079+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-12T04:37:09.079+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-12T04:37:09.084+0000] {configuration.py:1063} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-12T04:37:09.085+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-12T04:37:09.085+0000] {taskinstance.py:2005} ERROR - Failed to send email to: thanatthuch724@gmail.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_layer.py", line 57, in load_data_raw_zone
    pg_hook_load.copy_expert(sql=sql, filename=file_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 176, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.FeatureNotSupported: COPY delimiter must be a single one-byte character


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2418, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2003, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-12T04:37:09.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task raw_zone (COPY delimiter must be a single one-byte character
; 366)
[2024-01-12T04:37:09.104+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-12T04:37:09.120+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
